name: greenhouse_app
description: Greenhouse IoT monitoring and control app
publish_to: none
version: 1.0.0+1

environment:
  sdk: '>=3.3.0 <4.0.0'
  flutter: '>=3.19.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_riverpod: ^2.5.1
  mqtt_client: ^10.4.0
  flutter_secure_storage: ^9.2.2
  shared_preferences: ^2.3.3
  mobile_scanner: ^5.2.3
  go_router: ^14.6.2
  http: ^1.2.0
  multicast_dns: ^0.3.2
  cupertino_icons: ^1.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  mocktail: ^1.0.4

flutter:
  uses-material-design: true
