#!/bin/bash
# ═══════════════════════════════════════════════════════════════════════════
# Greenhouse IoT — host firewall (default-deny inbound)
# ═══════════════════════════════════════════════════════════════════════════
# Everything this unit exposes is authenticated now, but authentication is the
# last line, not the only one: a default-deny inbound policy means a service
# that gets accidentally exposed later (a debug listener, a future feature, a
# dependency opening a port) is not reachable unless it was deliberately
# allowed here.
#
#     sudo bash firewall.sh --dry-run   # print the rules, change nothing
#     sudo bash firewall.sh --apply     # apply, verify, auto-rollback on failure
#     sudo bash firewall.sh --status    # show what is currently loaded
#     sudo bash firewall.sh --flush     # remove all rules (back to wide open)
#
# LOCKOUT SAFETY — this script can cut your own SSH session, so:
#   * SSH (22) is allowed unconditionally, before any other rule;
#   * ESTABLISHED/RELATED is allowed first, so the session running this script
#     survives even the moment the policy flips to DROP;
#   * --apply verifies the ruleset loaded and that SSH is still permitted, and
#     rolls back automatically if either check fails;
#   * nothing here is enabled automatically. install.sh does NOT call this.
#     Enabling a firewall on a remote unit is a decision, not a default.
# ═══════════════════════════════════════════════════════════════════════════
set -e

MODE="${1:---dry-run}"
[ "$(id -u)" -eq 0 ] || { echo "Run with sudo."; exit 1; }

# Ports this project actually listens on. Anything not listed is dropped.
#   22   SSH — administration. ALWAYS allowed; removing it locks you out.
#   80   portal HTTP — captive portal + /pair existence check (must stay plain)
#   8443 portal HTTPS — pairing + history API
#   8883 mosquitto TLS — app/bridge MQTT
#   8090 cam_bridge — camera snapshot intake (signed + encrypted)
#   5353 mDNS/UDP — "Find my greenhouse" discovery
#   67   DHCP/UDP + 53 DNS — only meaningful in AP mode, where the Pi serves
#        the setup hotspot; harmless otherwise since nothing listens.
# Deliberately NOT opened: 1883 (mosquitto plaintext) — it binds 127.0.0.1
# only, and must never become reachable off-box.
# 443 is deliberately NOT here: nothing serves it. The portal's HTTPS is on
# 8443. Opening a port "just in case" is exactly what default-deny exists to
# prevent, and pi/tests/test_firewall_rules.py fails if this list drifts away
# from the services actually configured in this repo.
TCP_PORTS="22 80 8443 8883 8090"
UDP_PORTS="5353 67 53"

_rules() {
  cat <<EOF
# --- greenhouse firewall (generated by firewall.sh) ---
*filter
:INPUT DROP [0:0]
:FORWARD ACCEPT [0:0]
:OUTPUT ACCEPT [0:0]
# Existing connections first: keeps the SSH session that runs this alive
# through the policy change.
-A INPUT -m conntrack --ctstate ESTABLISHED,RELATED -j ACCEPT
-A INPUT -i lo -j ACCEPT
# SSH before anything else — the lockout guard.
-A INPUT -p tcp --dport 22 -j ACCEPT
EOF
  for p in $TCP_PORTS; do
    [ "$p" = "22" ] && continue
    echo "-A INPUT -p tcp --dport $p -j ACCEPT"
  done
  for p in $UDP_PORTS; do
    echo "-A INPUT -p udp --dport $p -j ACCEPT"
  done
  cat <<EOF
# ICMP: keep ping working. deploy.ps1 resolves the Pi by pinging it, so
# dropping this breaks the documented deploy path.
-A INPUT -p icmp -j ACCEPT
COMMIT
EOF
}

case "$MODE" in
  --dry-run)
    echo "==> Rules that WOULD be applied (nothing changed):"
    echo ""
    _rules
    echo ""
    echo "Run with --apply to load them."
    ;;

  --status)
    iptables -S INPUT 2>/dev/null || echo "(no iptables rules / iptables unavailable)"
    ;;

  --flush)
    iptables -P INPUT ACCEPT
    iptables -F INPUT
    echo "Firewall flushed — all inbound allowed again."
    ;;

  --apply)
    command -v iptables-restore >/dev/null || { echo "iptables-restore missing"; exit 1; }
    BACKUP=$(mktemp)
    iptables-save > "$BACKUP" 2>/dev/null || true
    echo "==> Backed up current rules to $BACKUP"

    if ! _rules | iptables-restore -n; then
      echo "ERROR: ruleset failed to load — nothing changed."
      exit 1
    fi

    # Verify the two things that matter: the policy actually flipped, and SSH
    # is still explicitly permitted. If either is wrong, roll back rather than
    # leave a unit we may have just cut ourselves off from.
    OK=1
    iptables -S INPUT | grep -q '^-P INPUT DROP' || OK=0
    iptables -S INPUT | grep -q '\-\-dport 22 -j ACCEPT' || OK=0
    if [ "$OK" -ne 1 ]; then
      echo "ERROR: post-apply verification failed — rolling back."
      iptables-restore < "$BACKUP" 2>/dev/null || iptables -P INPUT ACCEPT
      exit 1
    fi

    echo "==> Applied. Inbound default-deny; SSH/portal/MQTT/cam/mDNS allowed."
    echo ""
    echo "    These rules are NOT persistent across reboot by design — if this"
    echo "    locks you out of anything, power-cycling the Pi clears them."
    echo "    Once you have confirmed everything still works, make them stick:"
    echo "      sudo apt-get install -y iptables-persistent"
    echo "      sudo netfilter-persistent save"
    ;;

  *)
    echo "Usage: $0 [--dry-run|--apply|--status|--flush]"
    exit 1
    ;;
esac
