#!/usr/bin/env python3
"""Generate a sensor's AppKey, the header to flash it with, and its QR label.

Run once per physical sensor before flashing it. The QR is the ONLY copy of the
key besides the sensor itself and the Pi, so print it and stick it on the box.
"""
import argparse
import json
import os
import secrets

import qrcode

HEADER_TEMPLATE = '''// Generated by provision_sensor.py — one sensor, one key. Do not commit.
#pragma once
#include <stdint.h>
static const uint8_t NODE_APP_KEY[16] = { %s };
'''


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument('--mac', required=True, help='sensor MAC, any separator style')
    ap.add_argument('--out', default='.', help='directory for the QR and header')
    args = ap.parse_args()

    mac = ''.join(c for c in args.mac if c.isalnum()).upper()
    if len(mac) != 12:
        raise SystemExit(f'not a MAC address: {args.mac}')

    key = secrets.token_bytes(16)
    payload = json.dumps({'v': 1, 'mac': mac, 'k': key.hex()}, separators=(',', ':'))

    os.makedirs(args.out, exist_ok=True)
    qr_path = os.path.join(args.out, f'sensor-{mac}.png')
    qrcode.make(payload).save(qr_path)

    header_path = os.path.join(args.out, f'node_key-{mac}.h')
    body = ', '.join(f'0x{b:02X}' for b in key)
    with open(header_path, 'w') as fh:
        fh.write(HEADER_TEMPLATE % body)
    os.chmod(header_path, 0o600)

    import sys
    if hasattr(sys.stdout, 'reconfigure'):
        sys.stdout.reconfigure(encoding='utf-8', errors='replace')

    print(f'MAC     : {mac}')
    print(f'QR      : {qr_path}   \u2190 print and stick on the sensor')
    print(f'Header  : {header_path}')
    print(f'  Copy/rename this to "node_key.h" inside whichever sketch folder')
    print(f'  matches this board (firmware/edge_node_esp32_c3/ or')
    print(f'  firmware/edge_node_esp32/), overwriting the placeholder there,')
    print(f'  then compile and flash. node_key.h is gitignored -- it never gets')
    print(f'  committed.')
    print('This key exists nowhere else. Losing both the QR and the sensor means '
          'the sensor can never be re-enrolled.')


if __name__ == '__main__':
    main()
